apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container-test
          image: "gcr.io/felo-task-service-project/gke-test-nginx-0.1:latest"
          ports:
            - containerPort: 80
