name: Build and Upload to GCR

on:
  workflow_dispatch:
    inputs:
      cd-pipeline:
        description: 'spinnaker or gitactions?'     
        required: true
        default: 'spinnaker'

  push:
    branches:
      - main


env:
  PROJECT_ID: felo-task-service-project
  GKE_CLUSTER: three-tier-gke-cluster   # Add your cluster name here.
  GKE_ZONE: us-east1  # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.
  IMAGE: gke-test-nginx-0.1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:${{ github.event.inputs.cd-pipeline }}-$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:${{ github.event.inputs.cd-pipeline }}-$GITHUB_SHA"
